// Generated by https://quicktype.io

export interface DeleteImage {
    status: string;
    result: Result;
}

export interface Result {
    code: string;
    msg:  Msg;
}

export interface Msg {
    "delete image: ": string;
}
